/*
 * adc_src.c
 *
 *  Created on: 18 Jan 2023
 *      Author: Ahmed
 */

#include "../../SERV/bit_math.h"
#include "../../SERV/stdtypes.h"
#include "adc_init.h"
#include "adc_reg.h"
void ADC_INIT(void)
{
	/*
	 * Enable ADC
	 */
	SET_BIT(ADCSRA_REG,ADEN);

	/*
	 * SELECT ADC INPUT SOURCE
	 */
#if	ADC_INPUT_REFRENCE==ADC_EXTERNAL_INPUT
	CLR_BIT(ADMUX_REG,REFS0);
	CLR_BIT(ADMUX_REG,REFS1);
#elif ADC_INPUT_REFRENCE==ADC_INTERNAL_VCC
	SET_BIT(ADMUX_REG,REFS0);
	CLR_BIT(ADMUX_REG,REFS1);
#elif ADC_INPUT_REFRENCE==ADC_INTERNAL_2_56V
	SET_BIT(ADMUX_REG,REFS0);
	SET_BIT(ADMUX_REG,REFS1);
#endif
	/*
	 * Select PRESCALER
	 */
	ADCSRA_REG|=ADC_PRESCALER_SELECTOR;

	/*
	 * ADJUST RESULT EITHER LEFT OR RIGHT
	 */
#if ADC_ADJUST_RESULT== ADC_ADJUST_RIGHT
	CLR_BIT(ADCSRA_REG,ADLAR);
#elif ADC_ADJUST_RESULT== ADC_ADJUST_LEFT
	SET_BIT(ADCSRA_REG,ADLAR);
#endif

}

uint16 ADC_u16_Read_(void)
{
	/*
	 * Select Channel
	 */
	ADMUX_REG&=CLEAR_MUX_MUSK;
	ADMUX_REG|=ADC_MUX_CHANNEL_SELECTOR;
	/*
	 * CONVERSION MODE
	 */
#if	 ADC_CONVERSION_MODE == ADC_SINGLE_CONFERSION
		SET_BIT(ADCSRA_REG,ADSC);
		CLR_BIT(ADCSRA_REG,ADATE);
		while(GET_BIT(ADCSRA_REG,ADIF)==0);
		SET_BIT(ADCSRA_REG,ADIF);
		/*
		 * RETURN REGISTER ONLY LEFT.
		 */
		uint16 ADC_Val=ADC_REG;
#elif	ADC_CONVERSION_MODE==ADC_AUTO_TRIGGER_SOURCE
		SFIOR_REG|=ADC_TRIGGER_MODE;
		SET_BIT(ADCSRA_REG,ADSC);
		SET_BIT(ADCSRA_REG,ADATE);
#endif


	return ADC_Val;
}






